README.md

Create AUR git package

---

README.md
src/app.rs
src/config.rs
src/main.rs
src/menu.rs

Add Bottom status bar position

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
src/app.rs
src/centerbox.rs
src/config.rs
src/menu.rs
src/modules/mod.rs
src/modules/settings/battery.rs
src/modules/settings/mod.rs
src/modules/updates.rs
src/style.rs
src/utils/battery.rs
src/utils/idle_inhibitor.rs
src/utils/mod.rs

Add CI checks

---

.github/workflows/nix-ci.yml
Cargo.lock
Cargo.toml
README.md
flake.lock
flake.nix

10 - Add nix package support

---

src/app.rs
src/menu.rs
src/modules/clock.rs
src/modules/launcher.rs
src/modules/privacy.rs
src/modules/settings/audio.rs
src/modules/settings/bluetooth.rs
src/modules/settings/mod.rs
src/modules/settings/power.rs
src/modules/settings/upower.rs
src/modules/system_info.rs
src/modules/title.rs
src/modules/updates.rs
src/modules/workspaces.rs
src/password_dialog.rs
src/style.rs

19 Cleanup codebase

---

README.md

5 Update install instructions

---

src/modules/settings/mod.rs
src/modules/settings/network.rs
src/services/network/dbus.rs
src/services/network/mod.rs

I forgot to re-add this feature during the service refactor

Fix Vpn connection

---

CHANGELOG.md
src/app.rs
src/components/icons.rs
src/menu.rs
src/modules/privacy.rs
src/services/privacy.rs
src/style.rs

Add webcam monitoring and remove privacy sub-menu

Privacy module update

---

Cargo.lock

Fix cargo vendor

---

CHANGELOG.md
src/config.rs
src/modules/workspaces.rs
src/style.rs

Fix workspace text color

---

README.md

I would really like to help with the code, but so far I'm just learning RUST.
I'll start with this.

add ALT Linux install instruction

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
src/app.rs
src/config.rs
src/main.rs
src/modules/title.rs
src/modules/workspaces.rs

Closes #62 
Bonus:
Resolve a crash when the title module try to split a multi-byte char

Add special workspace support

---

CHANGELOG.md
src/services/upower/mod.rs
src/utils/launcher.rs

76 - Fix no battery indicator displayed

---

CHANGELOG.md
src/services/bluetooth/mod.rs

96 Fix NixOs bluetooth service

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
flake.lock
flake.nix
src/app.rs
src/modules/settings/mod.rs
src/outputs.rs
src/services/brightness.rs

Brightness Service Refactor & module refactor fixes

---

.github/workflows/nix-ci.yml
CHANGELOG.md
src/services/bluetooth/dbus.rs

104 - Fix bluetooth battery

---

CHANGELOG.md
README.md
src/config.rs
src/main.rs

112 add font config

---

README.md

Small update to the `README`, with working configuration for NixOS and/or home-manager. lmk if you want to me to change anything.

update nixos readme

---

CHANGELOG.md
Cargo.toml
README.md
src/app.rs
src/components/icons.rs
src/config.rs
src/menu.rs
src/modules/system_info.rs
src/modules/tray.rs
src/services/brightness.rs
src/services/mpris/mod.rs

Enhance sys module

---

src/modules/mod.rs
src/style.rs

Fix opacity for Group modules

---

CHANGELOG.md
README.md
src/app.rs
src/config.rs
src/modules/workspaces.rs

Resolves #136 
The new option `max_workspaces` only works if `enable_workspace_filling` is set to true.
There's also a bit of refactoring to simplify and speed up the code.

Add an option to specify the number of workspaces

---

src/modules/settings/mod.rs
src/modules/settings/network.rs

#154 - Hide VPN when there are no vpn connections 

---

src/services/network/dbus.rs

FIX: skip connections where settings can't be fetched

---

CHANGELOG.md
Cargo.lock
README.md
flake.lock
src/app.rs
src/config.rs
src/main.rs
src/outputs.rs
website/docs/configuration/appearance/general.md
website/docs/configuration/appearance/index.md

Add scale_factor config
